version: '3.8'

services:
  #  db:
  #    image: nouchka/sqlite3:latest
  #    volumes:
  #      - ./data/db:/root/db
  #    environment:
  #      - SQLITE3_DB=db.sqlite3
  app:
    build:
      context: .
    container_name: django-app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input --clear &&
             gunicorn djangodrf.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
#      - static_volume:/usr/src/app/static
      #      - media_volume:/usr/src/app/media
        - static:/user/src/app/static/
        - media:/user/src/app/media/
#    env_file:
#      - ./.env/dev.env


  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/user/src/app/static
      - media:/user/src/app/media

volumes:
  static:
  media:
