# Generated by Django 5.0.6 on 2024-09-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductView',
            new_name='ProductViewModel',
        ),
    ]
